# mern/compose.yaml

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5050:5050"
    env_file:
      - ./server/config.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend

    depends_on:
      backend:
        condition: service_healthy

    ports:
      - "8080:80"
