# mern/compose.yaml

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5050:5050"
    env_file:
      - ./server/config.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:80"
