# mern/Dockerfile-backend

FROM node:22-alpine

WORKDIR /app/server

# install dependencies
COPY server/package*.json ./
RUN npm ci

# Copy server code
COPY server/ .

# Copy environment variables
COPY server/config.env ./config.env

# Expose API port
EXPOSE 5050

# start server
CMD ["npm", "start"]
