# mern/client/Dockerfile-backend-frontend

# FASE 1 — FRONT-END BUILD
FROM node:22-alpine AS build


WORKDIR /app/client

# install dependencies
COPY client/package*.json ./
RUN npm ci

# copy code and generate /dist
COPY client .
RUN npm run build


# FASE 2 —  NGINX
FROM nginx:stable-alpine

# copy static files to NGINX
COPY --from=build /app/client/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose door 80
EXPOSE 80

# NGINX already starts automatically