# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-lab
  template:
    metadata:
      labels:
        app: nginx-lab
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
